site_name: Code Platoon Documentation
site_description: Documentation for code platoon apps
site_author: Gary Coffey
docs_dir: docs
site_dir: site
repo_name: CodePlatoonAlumni/docs
repo_url: https://github.com/CodePlatoonAlumni/docs
nav:
  - Home: 'index.md'
  - Alumni App:
    - Intro: 'documentation/alumni_app/index.md'
    - Example: https://github.com/CodePlatoonAlumni/alumni-fe
    - Markdown Cheatsheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences