site_name: Code Platoon Documentation
site_description: Documentation for code platoon apps
site_author: Gary Coffey
docs_dir: docs
site_dir: site
repo_name: CodePlatoonAlumni/docs
repo_url: https://github.com/CodePlatoonAlumni/docs
nav:
  - Home: 'index.md'
  - Alumni App:
    - Intro: 'alumni_app/index.md'
    - Front End Setup: 'alumni/react.md'
    - Design Docs: 'alumni_app/design_docs.md'
  - Amplify: 'amplify/index.md'
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences